install.packages(c("tidyverse", "devtools", "phaseR", "deSolve", "gganimate", "gifski"))
library(devtools)
install_github("dgrtwo/gganimate")
install_github('talgalili/installr')
library(installr)
install.ImageMagick()
